name: analytics_repository
description: Package which manages the analytics domain.
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  equatable: ^2.0.0
  firebase_analytics: ^11.1.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
